### ISSUE TITLE
Invoker should support local checkout

### ISSUE THREAD

**Issue by cunningt** [project-ncl/sourceclear-invoker#88]
SourceClear's scm tool supports running on a local checkout, which would allow quite a few features -

- ability to checkout not using sourceclear (you could checkout private repos more easily, and checkout protected repos like code.engineering repos)
- ability to patch the directory with settings.xml and srcclr.yml before running

**Comment by rnc** [comment]
It does support either `.` or `file:` URLs so I think it should work.
